WebTechPlayGround/Areas/ASPNET_MVC_PartialView/Controllers/ASPNET_MVC_PartialViewController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechPlayGround.Areas.ASPNET_MVC_PartialView.Controllers
{
    public class ASPNET_MVC_PartialViewController : Controller
    {
        // GET: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView
        public ActionResult Index()
        {
            return View();
        }

        // GET: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ASPNET_MVC_PartialView/ASPNET_MVC_PartialView/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

WebTechPlayGround/Areas/AngularJS/Controllers/AngularJSController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechPlayGround.Areas.AngularJS.Controllers
{
    public class AngularJSController : Controller
    {
        // GET: AngularJS/AngularJS
        public ActionResult Index()
        {
            return View();
        }
    }
}

WebTechPlayGround/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebTechPlayGround.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebTechPlayGround/Areas/ASPNET_MVC_PartialView/Views/ASPNET_MVC_PartialView/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>ASP.Net MVC Partial View Technologies</h2>

<ul>
    <li>@Html.ActionLink("1 test", "Index", "ASPNET_MVC_PartialView")</li>
</ul>

WebTechPlayGround/Areas/AngularJS/Views/AngularJS/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<h2>AngularJS (non-TypeScript)</h2>

<!-- the PlayAngularJs app scope is within this div tag -->
<div ng-app="PlayAngularJS"> 


    <!--  -->
</div>

WebTechPlayGround/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebTechPlayGround/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebTechPlayGround/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}


<ul>
    <li>@Html.ActionLink("Partial View Techs", "Index", "ASPNET_MVC_PartialView",new { area = "ASPNET_MVC_PartialView" }, new { })</li>
    <li>@Html.ActionLink("AngularJS Technology", "Index", "AngularJS", new { area = "AngularJS" }, new { })</li>
</ul>

WebTechPlayGround/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { })</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>